var assets = [{
    name: 'button',
    url: 'snd/btn.wav',
    type: ASSET_TYPE.SOUND
}, {
    name: 'ost',
    url: 'snd/ost.mp3',
    type: ASSET_TYPE.SOUND
}, {
    name: 'ball',
    url: 'snd/ball.wav',
    type: ASSET_TYPE.SOUND
}, {
    name: 'break',
    url: 'snd/break.wav',
    type: ASSET_TYPE.SOUND
}, {
    name: 'death',
    url: 'snd/death.wav',
    type: ASSET_TYPE.SOUND
}, {
    name: 'gameover',
    url: 'snd/gameover.wav',
    type: ASSET_TYPE.SOUND
}, {
    name: 'grow',
    url: 'snd/grow.wav',
    type: ASSET_TYPE.SOUND
}, {
    name: 'multiball',
    url: 'snd/multiball.wav',
    type: ASSET_TYPE.SOUND
}, {
    name: 'high',
    url: 'snd/high.wav',
    type: ASSET_TYPE.SOUND
}];